version: '3.7'
services:
  jupyter:
    labels:
      version: $IMAGE_VERSION
      maintainer: $MAINTAINER
    container_name: $CONTAINER_NAME
    build:
      context: .
      args:
        PYTHON_VERSION: $PYTHON_VERSION
        SQLITE_FILE: $SQLITE_FILE
        SQLITE_URL: $SQLITE_URL
    image: $DOCKER_HUB_ID/$IMAGE_NAME:$IMAGE_VERSION
    command: bash /root/workspace/up.sh $JUPYTER_PORT
    logging:
      driver: 'json-file'
    ports:
      - '$JUPYTER_PORT:$JUPYTER_PORT'
      - '$TENSOR_BOARD_PORT:$TENSOR_BOARD_PORT'
    volumes:
      - ./workspace:/root/workspace
